[package]
name = "hello-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["secrets", "tls", "json", "mtls"] }
rocket_dyn_templates = { version = "0.1", features = ["tera"] }
serde = { version = "1.0", features = ["derive"] }
